/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.awt.Color;
import java.awt.Container;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author JK.otmane
 */
public class Calcul extends javax.swing.JFrame implements Calculator{

   
    public Calcul() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        C = new javax.swing.JButton();
        CE = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        MC = new javax.swing.JButton();
        number1 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        inv = new javax.swing.JButton();
        inv1 = new javax.swing.JButton();
        produit = new javax.swing.JButton();
        mod = new javax.swing.JButton();
        diff = new javax.swing.JButton();
        somme = new javax.swing.JButton();
        inv_1 = new javax.swing.JButton();
        egale = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        number9 = new javax.swing.JButton();

        jButton7.setText("jButton1");

        jButton9.setText("jButton1");

        jButton13.setText("jButton1");

        jButton16.setText("jButton1");

        jButton18.setText("jButton1");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        C.setBackground(new java.awt.Color(0, 0, 0));
        C.setForeground(new java.awt.Color(255, 255, 255));
        C.setText("C");
        C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        CE.setBackground(new java.awt.Color(0, 0, 0));
        CE.setForeground(new java.awt.Color(255, 255, 255));
        CE.setText("CE");
        CE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("<--");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        number8.setBackground(new java.awt.Color(0, 0, 0));
        number8.setForeground(new java.awt.Color(255, 255, 255));
        number8.setText("8");
        number8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        number8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number8MouseExited(evt);
            }
        });
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ActionPerformed(evt);
            }
        });

        number7.setBackground(new java.awt.Color(0, 0, 0));
        number7.setForeground(new java.awt.Color(255, 255, 255));
        number7.setText("7");
        number7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        number7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number7MouseExited(evt);
            }
        });
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });

        number5.setBackground(new java.awt.Color(0, 0, 0));
        number5.setForeground(new java.awt.Color(255, 255, 255));
        number5.setText("5");
        number5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        number5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number5MouseExited(evt);
            }
        });
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ActionPerformed(evt);
            }
        });

        number4.setBackground(new java.awt.Color(0, 0, 0));
        number4.setForeground(new java.awt.Color(255, 255, 255));
        number4.setText("4");
        number4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        number4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number4MouseExited(evt);
            }
        });
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ActionPerformed(evt);
            }
        });

        MC.setBackground(new java.awt.Color(0, 0, 0));
        MC.setForeground(new java.awt.Color(255, 255, 255));
        MC.setText("x2");
        MC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCActionPerformed(evt);
            }
        });

        number1.setBackground(new java.awt.Color(0, 0, 0));
        number1.setForeground(new java.awt.Color(255, 255, 255));
        number1.setText("1");
        number1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        number1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number1MouseExited(evt);
            }
        });
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });

        number6.setBackground(new java.awt.Color(0, 0, 0));
        number6.setForeground(new java.awt.Color(255, 255, 255));
        number6.setText("6");
        number6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        number6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number6MouseExited(evt);
            }
        });
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ActionPerformed(evt);
            }
        });

        number3.setBackground(new java.awt.Color(0, 0, 0));
        number3.setForeground(new java.awt.Color(255, 255, 255));
        number3.setText("3");
        number3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        number3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number3MouseExited(evt);
            }
        });
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });

        number2.setBackground(new java.awt.Color(0, 0, 0));
        number2.setForeground(new java.awt.Color(255, 255, 255));
        number2.setText("2");
        number2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        number2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number2MouseExited(evt);
            }
        });
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });

        number0.setBackground(new java.awt.Color(0, 0, 0));
        number0.setForeground(new java.awt.Color(255, 255, 255));
        number0.setText("0");
        number0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        number0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number0MouseExited(evt);
            }
        });
        number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(0, 0, 0));
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("+/-");
        jButton23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(0, 0, 0));
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText(".");
        jButton24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        inv.setBackground(new java.awt.Color(0, 0, 0));
        inv.setForeground(new java.awt.Color(255, 255, 255));
        inv.setText("/");
        inv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invActionPerformed(evt);
            }
        });

        inv1.setBackground(new java.awt.Color(0, 0, 0));
        inv1.setForeground(new java.awt.Color(255, 255, 255));
        inv1.setText("sqrt");
        inv1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv1ActionPerformed(evt);
            }
        });

        produit.setBackground(new java.awt.Color(0, 0, 0));
        produit.setForeground(new java.awt.Color(255, 255, 255));
        produit.setText("*");
        produit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        produit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produitActionPerformed(evt);
            }
        });

        mod.setBackground(new java.awt.Color(0, 0, 0));
        mod.setForeground(new java.awt.Color(255, 255, 255));
        mod.setText("%");
        mod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });

        diff.setBackground(new java.awt.Color(0, 0, 0));
        diff.setForeground(new java.awt.Color(255, 255, 255));
        diff.setText("-");
        diff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        diff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffActionPerformed(evt);
            }
        });

        somme.setBackground(new java.awt.Color(0, 0, 0));
        somme.setForeground(new java.awt.Color(255, 255, 255));
        somme.setText("+");
        somme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        somme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sommeActionPerformed(evt);
            }
        });

        inv_1.setBackground(new java.awt.Color(0, 0, 0));
        inv_1.setForeground(new java.awt.Color(255, 255, 255));
        inv_1.setText("1/X");
        inv_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inv_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_1ActionPerformed(evt);
            }
        });

        egale.setBackground(new java.awt.Color(0, 0, 0));
        egale.setForeground(new java.awt.Color(255, 255, 255));
        egale.setText("=");
        egale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        egale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egaleActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));

        number9.setBackground(new java.awt.Color(0, 0, 0));
        number9.setForeground(new java.awt.Color(255, 255, 255));
        number9.setText("9");
        number9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        number9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number9MouseExited(evt);
            }
        });
        number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(number1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(number4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(number7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(number2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(number5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(number0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(number3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(number6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(somme, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(egale, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(diff, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(number9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(inv1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(MC, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(inv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inv_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(produit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(result)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mod)
                    .addComponent(inv1)
                    .addComponent(MC)
                    .addComponent(inv_1))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CE)
                    .addComponent(C)
                    .addComponent(jButton4)
                    .addComponent(inv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number7)
                    .addComponent(number8)
                    .addComponent(number9)
                    .addComponent(produit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number4)
                    .addComponent(number5)
                    .addComponent(number6)
                    .addComponent(diff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1)
                    .addComponent(number2)
                    .addComponent(number3)
                    .addComponent(somme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number0)
                    .addComponent(jButton23)
                    .addComponent(jButton24)
                    .addComponent(egale))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"9");
    }//GEN-LAST:event_number9ActionPerformed

    private void number7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number7MouseEntered
        // TODO add your handling code here:
        number7.setBackground(Color.blue);
    }//GEN-LAST:event_number7MouseEntered

    private void number7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number7MouseExited
        // TODO add your handling code here:
        number7.setBackground(Color.black);
    }//GEN-LAST:event_number7MouseExited

    private void number8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number8MouseEntered
        // TODO add your handling code here:
        number8.setBackground(Color.blue);
    }//GEN-LAST:event_number8MouseEntered

    private void number8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number8MouseExited
        // TODO add your handling code here:
        number8.setBackground(Color.black);
    }//GEN-LAST:event_number8MouseExited

    private void number9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number9MouseEntered
        // TODO add your handling code here:
         number9.setBackground(Color.blue);
    }//GEN-LAST:event_number9MouseEntered

    private void number9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number9MouseExited
        // TODO add your handling code here:
        number9.setBackground(Color.black);
    }//GEN-LAST:event_number9MouseExited

    private void number6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number6MouseEntered
        // TODO add your handling code here:
         number6.setBackground(Color.blue);
    }//GEN-LAST:event_number6MouseEntered

    private void number6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number6MouseExited
        // TODO add your handling code here:
        number6.setBackground(Color.black);
    }//GEN-LAST:event_number6MouseExited

    private void number5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number5MouseEntered
        // TODO add your handling code here:
                number5.setBackground(Color.blue);

    }//GEN-LAST:event_number5MouseEntered

    private void number5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number5MouseExited
        // TODO add your handling code here:
          number5.setBackground(Color.black);
    }//GEN-LAST:event_number5MouseExited

    private void number4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number4MouseEntered
        // TODO add your handling code here:
        number4.setBackground(Color.blue);
    }//GEN-LAST:event_number4MouseEntered

    private void number4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number4MouseExited
        // TODO add your handling code here:
         number4.setBackground(Color.black);
    }//GEN-LAST:event_number4MouseExited

    private void number1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number1MouseEntered
        // TODO add your handling code here:
        number1.setBackground(Color.blue);
    }//GEN-LAST:event_number1MouseEntered

    private void number1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number1MouseExited
        // TODO add your handling code here:
        number1.setBackground(Color.black);
    }//GEN-LAST:event_number1MouseExited

    private void number0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number0MouseEntered
        // TODO add your handling code here:
        number0.setBackground(Color.blue);
    }//GEN-LAST:event_number0MouseEntered

    private void number0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number0MouseExited
        // TODO add your handling code here:
         number0.setBackground(Color.black);
    }//GEN-LAST:event_number0MouseExited

    private void number2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number2MouseEntered
        // TODO add your handling code here:
        number2.setBackground(Color.blue);
    }//GEN-LAST:event_number2MouseEntered

    private void number2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number2MouseExited
        // TODO add your handling code here:
          number2.setBackground(Color.black);
    }//GEN-LAST:event_number2MouseExited

    private void number3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number3MouseEntered
        // TODO add your handling code here:
         number3.setBackground(Color.blue);
    }//GEN-LAST:event_number3MouseEntered

    private void number3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number3MouseExited
        // TODO add your handling code here:
        number3.setBackground(Color.black);
    }//GEN-LAST:event_number3MouseExited

    private void number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"0");
    }//GEN-LAST:event_number0ActionPerformed

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"1");
    }//GEN-LAST:event_number1ActionPerformed

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"2");
    }//GEN-LAST:event_number2ActionPerformed

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"3");
    }//GEN-LAST:event_number3ActionPerformed

    private void number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"6");
    }//GEN-LAST:event_number6ActionPerformed

    private void number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"5");
    }//GEN-LAST:event_number5ActionPerformed

    private void number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"4");
    }//GEN-LAST:event_number4ActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"7");
    }//GEN-LAST:event_number7ActionPerformed

    private void number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"8");
    }//GEN-LAST:event_number8ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        if(!isDecimal){
            jTextField1.setText(jTextField1.getText()+".");
            isDecimal=true;
        }
         
    }//GEN-LAST:event_jButton24ActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        result.setText("");
        
    }//GEN-LAST:event_CActionPerformed

    private void CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEActionPerformed
        // TODO add your handling code here:
         jTextField1.setText("");
    }//GEN-LAST:event_CEActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        String value=jTextField1.getText();
        if(!value.contains("-")){
            jTextField1.setText('-'+value);
        }else{
            try {
                jTextField1.setText(value.split("-")[1]);
            } catch (IndexOutOfBoundsException e) {
                jTextField1.setText("");
            }
        }
        
    }//GEN-LAST:event_jButton23ActionPerformed

    @Override
    public void add(double a, double b) {
        setResult(a+b);
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void substract(double a, double b) {
         setResult(a-b);
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void multiply(double a, double b) {
         setResult(a*b);
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void divide(double a, double b) {
         setResult(a/b);
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    private void setResult(double result){
      jTextField1.setText(Double.toString(result));
      this.result.setText("");
  }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String value =jTextField1.getText();
        int length =value.length();
        if(length > 0){
            StringBuilder builder=new StringBuilder(value);
            builder.deleteCharAt(length - 1);
            jTextField1.setText(builder.toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    public void  storeToBeCalcultedValue(String sign){
         String value=jTextField1.getText();
         toBeCalcultedValue =Double.parseDouble(value);
         result.setText(value+" "+sign);
         jTextField1.setText("");
     }
    private void invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invActionPerformed
        // TODO add your handling code here:
        sign="/";
        if(jTextField1.getText().length()>0){
            storeToBeCalcultedValue(sign);
        }
        
    }//GEN-LAST:event_invActionPerformed

    private void produitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produitActionPerformed
        // TODO add your handling code here:
        sign="*";
        if(jTextField1.getText().length()>0){
         storeToBeCalcultedValue(sign);
        }
    }//GEN-LAST:event_produitActionPerformed

    private void diffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffActionPerformed
        // TODO add your handling code here:
        sign="-";
        if(jTextField1.getText().length()>0){
         storeToBeCalcultedValue(sign);
        }
    }//GEN-LAST:event_diffActionPerformed
    
    private void sommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sommeActionPerformed
        // TODO add your handling code here:
        sign="+";
        if(jTextField1.getText().length()>0){
        storeToBeCalcultedValue(sign);
        }
    }//GEN-LAST:event_sommeActionPerformed

    private void egaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egaleActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().length()>0){
            double b=Double.parseDouble(jTextField1.getText());
            switch(sign){
                case "+":
                    add(toBeCalcultedValue, b);
                    break;
                case "-":
                    substract(toBeCalcultedValue, b);
                    break;
                case "*":
                    multiply(toBeCalcultedValue, b);
                    break;
                case "/":
                    divide(toBeCalcultedValue, b);
                    break;
            }
        }
    }//GEN-LAST:event_egaleActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        // TODO add your handling code here:
        if(result.getText().length() >0 && jTextField1.getText().length()>0){
            toBeCalcultedValue =Double.parseDouble(jTextField1.getText());
            porstange(Double.parseDouble(result.getText().split(" ")[0]),toBeCalcultedValue);
        }
    }//GEN-LAST:event_modActionPerformed

    private void inv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv1ActionPerformed
        // TODO add your handling code here:
        toBeCalcultedValue =Double.parseDouble(jTextField1.getText());
        sqrtRoot(toBeCalcultedValue);
    }//GEN-LAST:event_inv1ActionPerformed

    private void MCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().length()>0){
            toBeCalcultedValue =Double.parseDouble(jTextField1.getText());
            square(toBeCalcultedValue);
        }
        
    }//GEN-LAST:event_MCActionPerformed
     private void oneByX(double a){
         jTextField1.setText(Double.toString(1/a));
     }
    private void inv_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().length()>0){
            toBeCalcultedValue =Double.parseDouble(jTextField1.getText());
            oneByX(toBeCalcultedValue);
        }
    }//GEN-LAST:event_inv_1ActionPerformed
    private void square(double a){
        jTextField1.setText(Double.toString(a*=a));
    }
    private void sqrtRoot(double a){
        jTextField1.setText(Double.toString(Math.sqrt(a)));
    }
    public void porstange(double a , double b){
        switch(sign){
            case "+":
               add(((a*b)/100), a);
               break;
            case "-":
               substract(((a*b)/100), a);
               break;
            case "*":
               multiply(((a*b)/100), a);
               break;
            case "/":
               divide(((a*b)/100), a);
               break;
        
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
                    
                    new Calcul().setVisible(true);
               
            }
        });
    }
    private String sign;
     private boolean isDecimal=false;
     private  double toBeCalcultedValue;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C;
    private javax.swing.JButton CE;
    private javax.swing.JButton MC;
    private javax.swing.JButton diff;
    private javax.swing.JButton egale;
    private javax.swing.JButton inv;
    private javax.swing.JButton inv1;
    private javax.swing.JButton inv_1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton mod;
    private javax.swing.JButton number0;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JButton produit;
    private javax.swing.JLabel result;
    private javax.swing.JButton somme;
    // End of variables declaration//GEN-END:variables

   
}
